# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_MEMORY = 6144
VM_CPUS = 4

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora28"
  config.vm.hostname = "devstack-fedora-ovs"
  config.ssh.forward_agent = true

  config.vm.define "devstack-fedora-ovs" do |devstack|
    end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Private (host-only) network
  config.vm.network "private_network", ip: "10.110.0.20"

  # Libvirt specific configuration
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = VM_MEMORY
    libvirt.cpus = VM_CPUS
    libvirt.nested = true
    libvirt.machine_virtual_size = 100
  end

  # VirtualBox specific configuration
  config.vm.provider "virtualbox" do |vb|
      vb.name = "devstack-fedora-ovs"
      vb.memory = VM_MEMORY
      vb.cpus = VM_CPUS
  end

  # Preprovisioning with shell script
  # It's necessary because Fedora 27 don't have python2 installed by default
  # and it's required by ansible
  config.vm.provision "shell", inline: "sudo yum -y install python2"

  # Provisioning with a ansible.
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../../openstack_provisioning/openstack.yml"
      ansible.ask_vault_pass = true
      ansible.extra_vars = {
          "devstack_datafile" => "/tmp/devstack_data",
          "iface"             => "eth1",
          "vm_type"           => "devstack",
          "l2_agent"          => "openvswitch",
          "topology"          => "allinone",
      }
  end
end
