---
- hosts: all
  user: root
  tasks:
      - name: Upgrade all Centos packages
        dnf:
            name: '*'
            state: latest
        become: yes
        become_method: sudo
        when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux'


- name: provision instance
  hosts: all
  user: root
  roles:
      - { role: base }
      - { role: base_configs }
      - { role: fzf }
      - { role: development }
      - { role: tripleo }
      - { role: neutron }
