---
- hosts: all
  user: root
  tasks:
      - name: Upgrade all Centos packages
        yum:
            name: '*'
            state: latest
            update_cache: yes
        become: yes
        become_method: sudo
        when: ansible_distribution == "CentOS" or ansible_distribution == 'Red Hat Enterprise Linux'


- name: provision instance
  hosts: all
  user: root
  roles:
      - { role: base }
      - { role: base_configs }
      - { role: openvswitch }
      - { role: docker }
      - { role: fzf }
      - { role: development }
