# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_MEMORY = 4096
VM_CPUS = 2

iface = "eth0"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "osp-patcher"
  config.ssh.forward_agent = true

  config.vm.define "osp-patcher" do |osp_patcher|
    end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Private (host-only) network
  config.vm.network "private_network", ip: "10.110.0.60"

  # Libvirt specific configuration
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = VM_MEMORY
    libvirt.cpus = VM_CPUS
    libvirt.nested = true
    libvirt.machine_virtual_size = 100
    libvirt.qemu_use_session = false
  end

  # VirtualBox specific configuration
  config.vm.provider "virtualbox" do |vb|
      vb.name = "osp-patcher"
      vb.memory = VM_MEMORY
      vb.cpus = VM_CPUS
  end


  # Preprovisioning with shell script
  # It's necessary because Fedora 28 don't have python2 installed by default
  # and it's required by ansible
  config.vm.provision "shell", inline: "sudo yum -y install python2"

  # Provisioning with a ansible.
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
      ansible.ask_vault_pass = true
      ansible.extra_vars = {
          "iface"             => iface,
      }
  end
end
