# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_MEMORY = 8196
VM_CPUS = 4
iface = "ens6"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/centos-stream-9"
  config.vm.hostname = "fullstack-centos"
  config.ssh.forward_agent = true

  config.vm.define "fullstack-centos" do |fullstack|
    end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Private (host-only) network
  config.vm.network "private_network", ip: "10.220.0.41"

  # Libvirt specific configuration
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = VM_MEMORY
    libvirt.cpus = VM_CPUS
    libvirt.nested = true
    libvirt.machine_virtual_size = 100
    libvirt.qemu_use_session = false
  end

  # VirtualBox specific configuration
  config.vm.provider "virtualbox" do |vb|
      vb.name = "fullstack-centos"
      vb.memory = VM_MEMORY
      vb.cpus = VM_CPUS
  end

  # Provisioning with a ansible.
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../openstack_provisioning/openstack.yml"
      ansible.ask_vault_pass = true
      ansible.extra_vars = {
          "iface"             => iface,
          "vm_type"           => "fullstack",
      }
  end
end
