# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_MEMORY = 16384
VM_CPUS = 4

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "http://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-Vagrant-9-20240304.0.x86_64.vagrant-libvirt.box"
  config.vm.hostname = "generic-centos-vm"
  config.ssh.forward_agent = true

  config.vm.define "generic-centos-vm" do |vm|
    end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Private (host-only) network
  config.vm.network "private_network", ip: "10.110.0.50"

  # Libvirt specific configuration
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = VM_MEMORY
    libvirt.cpus = VM_CPUS
    libvirt.nested = true
    libvirt.machine_virtual_size = 100
    libvirt.qemu_use_session = false
  end

  # VirtualBox specific configuration
  config.vm.provider "virtualbox" do |vb|
      vb.name = "generic-centos-vm"
      vb.memory = VM_MEMORY
      vb.cpus = VM_CPUS
  end

  # Provisioning with a ansible.
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "./playbook.yml"
      ansible.ask_vault_pass = true
      ansible.extra_vars = {
          "iface"             => "eth1",
      }
  end
end
